const nav = [
        {
            "id": "",
            "type": "navigation",
            "params": {
                "channel_ename": "choice",
                "channel_id": "100101",
                "channel_name": "首页",
                "channel_type": "影视推荐",
                "default_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-choice.svg?max_age=7776000",
                "default_marklabel": "",
                "ext_params": "",
                "hover_icon": "",
                "is_open_new_tab": "false",
                "is_outside_channel": "false",
                "jump_url": "",
                "region_type": "0",
                "selected_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-choice-select.svg?max_age=7776000",
                "selected_icon_all": "",
                "text_marklabel": "",
                "unselected_icon_all": ""
            },
            "children_list": {},
            "report_infos": {},
            "operations": {},
            "flip_infos": {},
            "static_conf": null
        },
        {
            "id": "",
            "type": "navigation",
            "params": {
                "channel_ename": "",
                "channel_id": "00000",
                "channel_name": "VIP会员",
                "channel_type": "影视推荐",
                "default_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-hlw.svg?max_age=7776000",
                "default_marklabel": "",
                "ext_params": "",
                "hover_icon": "",
                "is_open_new_tab": "true",
                "is_outside_channel": "true",
                "jump_url": "https://film.qq.com/",
                "region_type": "0",
                "selected_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-hlw-select.svg?max_age=7776000",
                "selected_icon_all": "",
                "text_marklabel": "",
                "unselected_icon_all": ""
            },
            "children_list": {},
            "report_infos": {},
            "operations": {},
            "flip_infos": {},
            "static_conf": null
        },
        {
            "id": "",
            "type": "navigation",
            "params": {
                "channel_ename": "mid_video",
                "channel_id": "110852",
                "channel_name": "中视频",
                "channel_type": "就好这口",
                "default_icon": "https://vfiles.gtimg.cn/wupload/new_year.newyear_test/20230228_7dq8mzqey4ua9twjf44w2ftc6bcp71zw.svg?max_age=7776000",
                "default_marklabel": "",
                "ext_params": "",
                "hover_icon": "",
                "is_open_new_tab": "false",
                "is_outside_channel": "false",
                "jump_url": "",
                "region_type": "0",
                "selected_icon": "https://vfiles.gtimg.cn/wupload/new_year.newyear_test/20230228_y6m7mjr9ipxl9qbisfkx8ouorbbptmxa.svg?max_age=7776000",
                "selected_icon_all": "",
                "text_marklabel": "",
                "unselected_icon_all": ""
            },
            "children_list": {},
            "report_infos": {},
            "operations": {},
            "flip_infos": {},
            "static_conf": null
        },
        {
            "id": "",
            "type": "navigation",
            "params": {
                "channel_ename": "tv",
                "channel_id": "100113",
                "channel_name": "电视剧",
                "channel_type": "影视推荐",
                "default_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-tv.svg?max_age=7776000",
                "default_marklabel": "",
                "ext_params": "",
                "hover_icon": "",
                "is_open_new_tab": "false",
                "is_outside_channel": "false",
                "jump_url": "",
                "region_type": "0",
                "selected_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-tv-select.svg?max_age=7776000",
                "selected_icon_all": "",
                "text_marklabel": "",
                "unselected_icon_all": ""
            },
            "children_list": {},
            "report_infos": {},
            "operations": {},
            "flip_infos": {},
            "static_conf": null
        },
        {
            "id": "",
            "type": "navigation",
            "params": {
                "channel_ename": "movie",
                "channel_id": "100173",
                "channel_name": "电影",
                "channel_type": "影视推荐",
                "default_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-movie.svg?max_age=7776000",
                "default_marklabel": "",
                "ext_params": "",
                "hover_icon": "",
                "is_open_new_tab": "false",
                "is_outside_channel": "false",
                "jump_url": "",
                "region_type": "0",
                "selected_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-movie-select.svg?max_age=7776000",
                "selected_icon_all": "",
                "text_marklabel": "",
                "unselected_icon_all": ""
            },
            "children_list": {},
            "report_infos": {},
            "operations": {},
            "flip_infos": {},
            "static_conf": null
        },
        {
            "id": "",
            "type": "navigation",
            "params": {
                "channel_ename": "variety",
                "channel_id": "100109",
                "channel_name": "综艺",
                "channel_type": "影视推荐",
                "default_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-variety.svg?max_age=7776000",
                "default_marklabel": "",
                "ext_params": "",
                "hover_icon": "",
                "is_open_new_tab": "false",
                "is_outside_channel": "false",
                "jump_url": "",
                "region_type": "0",
                "selected_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-variety-select.svg?max_age=7776000",
                "selected_icon_all": "",
                "text_marklabel": "",
                "unselected_icon_all": ""
            },
            "children_list": {},
            "report_infos": {},
            "operations": {},
            "flip_infos": {},
            "static_conf": null
        },
        {
            "id": "",
            "type": "navigation",
            "params": {
                "channel_ename": "cartoon",
                "channel_id": "100119",
                "channel_name": "动漫",
                "channel_type": "影视推荐",
                "default_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-cartoon.svg?max_age=7776000",
                "default_marklabel": "",
                "ext_params": "",
                "hover_icon": "",
                "is_open_new_tab": "false",
                "is_outside_channel": "false",
                "jump_url": "",
                "region_type": "0",
                "selected_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-cartoon-select.svg?max_age=7776000",
                "selected_icon_all": "",
                "text_marklabel": "",
                "unselected_icon_all": ""
            },
            "children_list": {},
            "report_infos": {},
            "operations": {},
            "flip_infos": {},
            "static_conf": null
        },
        {
            "id": "",
            "type": "navigation",
            "params": {
                "channel_ename": "child",
                "channel_id": "100150",
                "channel_name": "少儿",
                "channel_type": "影视推荐",
                "default_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-child.svg?max_age=7776000",
                "default_marklabel": "",
                "ext_params": "",
                "hover_icon": "",
                "is_open_new_tab": "false",
                "is_outside_channel": "false",
                "jump_url": "",
                "region_type": "0",
                "selected_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-child-select.svg?max_age=7776000",
                "selected_icon_all": "",
                "text_marklabel": "",
                "unselected_icon_all": ""
            },
            "children_list": {},
            "report_infos": {},
            "operations": {},
            "flip_infos": {},
            "static_conf": null
        },
        {
            "id": "",
            "type": "navigation",
            "params": {
                "channel_ename": "nba",
                "channel_id": "100176",
                "channel_name": "NBA",
                "channel_type": "体育游戏",
                "default_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-nba.svg?max_age=7776000",
                "default_marklabel": "",
                "ext_params": "",
                "hover_icon": "",
                "is_open_new_tab": "false",
                "is_outside_channel": "false",
                "jump_url": "",
                "region_type": "0",
                "selected_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-nba-select.svg?max_age=7776000",
                "selected_icon_all": "",
                "text_marklabel": "",
                "unselected_icon_all": ""
            },
            "children_list": {},
            "report_infos": {},
            "operations": {},
            "flip_infos": {},
            "static_conf": null
        },
        {
            "id": "",
            "type": "navigation",
            "params": {
                "channel_ename": "doco",
                "channel_id": "100105",
                "channel_name": "纪录片",
                "channel_type": "影视推荐",
                "default_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-doco.svg?max_age=7776000",
                "default_marklabel": "",
                "ext_params": "",
                "hover_icon": "",
                "is_open_new_tab": "false",
                "is_outside_channel": "false",
                "jump_url": "",
                "region_type": "0",
                "selected_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-doco-select.svg?max_age=7776000",
                "selected_icon_all": "",
                "text_marklabel": "",
                "unselected_icon_all": ""
            },
            "children_list": {},
            "report_infos": {},
            "operations": {},
            "flip_infos": {},
            "static_conf": null
        },
        {
            "id": "",
            "type": "navigation",
            "params": {
                "channel_ename": "mini_drama",
                "channel_id": "110749",
                "channel_name": "短剧",
                "channel_type": "影视推荐",
                "default_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-tv.svg?max_age=7776000",
                "default_marklabel": "",
                "ext_params": "",
                "hover_icon": "",
                "is_open_new_tab": "false",
                "is_outside_channel": "false",
                "jump_url": "",
                "region_type": "0",
                "selected_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-tv-select.svg?max_age=7776000",
                "selected_icon_all": "",
                "text_marklabel": "",
                "unselected_icon_all": ""
            },
            "children_list": {},
            "report_infos": {},
            "operations": {},
            "flip_infos": {},
            "static_conf": null
        },
        {
            "id": "",
            "type": "navigation",
            "params": {
                "channel_ename": "olympics",
                "channel_id": "701110",
                "channel_name": "奥运会",
                "channel_type": "体育游戏",
                "default_icon": "https://vfiles.gtimg.cn/wuji_dashboard/xy/starter/40afc735.png",
                "default_marklabel": "",
                "ext_params": "",
                "hover_icon": "",
                "is_open_new_tab": "false",
                "is_outside_channel": "true",
                "jump_url": "https://v.qq.com/s/topic/v_nba/render/gToWaFyH.html",
                "region_type": "0",
                "selected_icon": "https://vfiles.gtimg.cn/wuji_dashboard/xy/starter/cdbfb03f.svg",
                "selected_icon_all": "",
                "text_marklabel": "",
                "unselected_icon_all": ""
            },
            "children_list": {},
            "report_infos": {},
            "operations": {},
            "flip_infos": {},
            "static_conf": null
        },
        {
            "id": "",
            "type": "navigation",
            "params": {
                "channel_ename": "sports_new",
                "channel_id": "100103",
                "channel_name": "体育",
                "channel_type": "体育游戏",
                "default_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-sports_new.svg?max_age=7776000",
                "default_marklabel": "",
                "ext_params": "",
                "hover_icon": "",
                "is_open_new_tab": "false",
                "is_outside_channel": "false",
                "jump_url": "",
                "region_type": "0",
                "selected_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-sports_new-select.svg?max_age=7776000",
                "selected_icon_all": "",
                "text_marklabel": "",
                "unselected_icon_all": ""
            },
            "children_list": {},
            "report_infos": {},
            "operations": {},
            "flip_infos": {},
            "static_conf": null
        },
        {
            "id": "",
            "type": "navigation",
            "params": {
                "channel_ename": "",
                "channel_id": "0000",
                "channel_name": "爱玩",
                "channel_type": "体育游戏",
                "default_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-games.svg?max_age=7776000",
                "default_marklabel": "",
                "ext_params": "",
                "hover_icon": "",
                "is_open_new_tab": "false",
                "is_outside_channel": "true",
                "jump_url": "https://iwan.video.qq.com/game-community/game-center/home?ztid=km53eytfwg\u0026iwankey=iwan_pc_channel-10029421_rpk",
                "region_type": "0",
                "selected_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-games-select.svg?max_age=7776000",
                "selected_icon_all": "",
                "text_marklabel": "",
                "unselected_icon_all": ""
            },
            "children_list": {},
            "report_infos": {},
            "operations": {},
            "flip_infos": {},
            "static_conf": null
        },
        {
            "id": "",
            "type": "navigation",
            "params": {
                "channel_ename": "game_new",
                "channel_id": "110507",
                "channel_name": "游戏",
                "channel_type": "体育游戏",
                "default_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-games.svg?max_age=7776000",
                "default_marklabel": "",
                "ext_params": "",
                "hover_icon": "",
                "is_open_new_tab": "false",
                "is_outside_channel": "false",
                "jump_url": "",
                "region_type": "0",
                "selected_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-games-select.svg?max_age=7776000",
                "selected_icon_all": "",
                "text_marklabel": "",
                "unselected_icon_all": ""
            },
            "children_list": {},
            "report_infos": {},
            "operations": {},
            "flip_infos": {},
            "static_conf": null
        },
        {
            "id": "",
            "type": "navigation",
            "params": {
                "channel_ename": "",
                "channel_id": "00000",
                "channel_name": "传奇游戏库",
                "channel_type": "体育游戏",
                "default_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-legend_game.svg?max_age=7776000",
                "default_marklabel": "https://vfiles.gtimg.cn/wupload/new_year.newyear_test/20221124_hwbe9ca1dki2nmk1wy9p8vsmt9wct6v8.png",
                "ext_params": "",
                "hover_icon": "",
                "is_open_new_tab": "false",
                "is_outside_channel": "true",
                "jump_url": "https://iwan.video.qq.com/game-community/game-center/home?ztid=p7hq7qfq2m\u0026iwankey=iwan_pc_channel-10086082_rpk",
                "region_type": "0",
                "selected_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-legend_game-select.svg?max_age=7776000",
                "selected_icon_all": "",
                "text_marklabel": "",
                "unselected_icon_all": ""
            },
            "children_list": {},
            "report_infos": {},
            "operations": {},
            "flip_infos": {},
            "static_conf": null
        },
        {
            "id": "",
            "type": "navigation",
            "params": {
                "channel_ename": "tech",
                "channel_id": "100169",
                "channel_name": "科技",
                "channel_type": "资讯前沿",
                "default_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-tech.svg?max_age=7776000",
                "default_marklabel": "",
                "ext_params": "",
                "hover_icon": "",
                "is_open_new_tab": "false",
                "is_outside_channel": "false",
                "jump_url": "",
                "region_type": "0",
                "selected_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-tech-select.svg?max_age=7776000",
                "selected_icon_all": "",
                "text_marklabel": "",
                "unselected_icon_all": ""
            },
            "children_list": {},
            "report_infos": {},
            "operations": {},
            "flip_infos": {},
            "static_conf": null
        },
        {
            "id": "",
            "type": "navigation",
            "params": {
                "channel_ename": "music",
                "channel_id": "100118",
                "channel_name": "音乐",
                "channel_type": "乐享生活",
                "default_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-music.svg?max_age=7776000",
                "default_marklabel": "",
                "ext_params": "",
                "hover_icon": "",
                "is_open_new_tab": "false",
                "is_outside_channel": "false",
                "jump_url": "",
                "region_type": "0",
                "selected_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-music-select.svg?max_age=7776000",
                "selected_icon_all": "",
                "text_marklabel": "",
                "unselected_icon_all": ""
            },
            "children_list": {},
            "report_infos": {},
            "operations": {},
            "flip_infos": {},
            "static_conf": null
        },
        {
            "id": "",
            "type": "navigation",
            "params": {
                "channel_ename": "f1",
                "channel_id": "00000",
                "channel_name": "F1",
                "channel_type": "体育游戏",
                "default_icon": "https://media-img.puui.qpic.cn/media_img/0/lena/PICr8p8c3_72_72/0",
                "default_marklabel": "",
                "ext_params": "",
                "hover_icon": "",
                "is_open_new_tab": "false",
                "is_outside_channel": "true",
                "jump_url": "https://v.qq.com/s/topic/v_sports/render/uX0ceyb1.html",
                "region_type": "0",
                "selected_icon": "https://media-img.puui.qpic.cn/media_img/0/lena/PIC43c3c1_72_72/0",
                "selected_icon_all": "",
                "text_marklabel": "",
                "unselected_icon_all": ""
            },
            "children_list": {},
            "report_infos": {},
            "operations": {},
            "flip_infos": {},
            "static_conf": null
        },
        {
            "id": "",
            "type": "navigation",
            "params": {
                "channel_ename": "",
                "channel_id": "00000",
                "channel_name": "WWE",
                "channel_type": "体育游戏",
                "default_icon": "https://vm.gtimg.cn/z/static/channel-icons/wwe-normal.svg?max_age=7776000",
                "default_marklabel": "",
                "ext_params": "",
                "hover_icon": "",
                "is_open_new_tab": "false",
                "is_outside_channel": "true",
                "jump_url": "https://v.qq.com/s/topic/v_sports/render/cE4QHP4K.html",
                "region_type": "0",
                "selected_icon": "https://vm.gtimg.cn/z/static/channel-icons/wwe-select.svg?max_age=7776000",
                "selected_icon_all": "",
                "text_marklabel": "",
                "unselected_icon_all": ""
            },
            "children_list": {},
            "report_infos": {},
            "operations": {},
            "flip_infos": {},
            "static_conf": null
        },
        {
            "id": "",
            "type": "navigation",
            "params": {
                "channel_ename": "knowledge",
                "channel_id": "110617",
                "channel_name": "知识",
                "channel_type": "就好这口",
                "default_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-knowledge.svg?max_age=7776000",
                "default_marklabel": "",
                "ext_params": "",
                "hover_icon": "",
                "is_open_new_tab": "false",
                "is_outside_channel": "false",
                "jump_url": "",
                "region_type": "0",
                "selected_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-knowledge-select.svg?max_age=7776000",
                "selected_icon_all": "",
                "text_marklabel": "",
                "unselected_icon_all": ""
            },
            "children_list": {},
            "report_infos": {},
            "operations": {},
            "flip_infos": {},
            "static_conf": null
        },
        {
            "id": "",
            "type": "navigation",
            "params": {
                "channel_ename": "education",
                "channel_id": "100155",
                "channel_name": "学堂",
                "channel_type": "就好这口",
                "default_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-education.svg?max_age=7776000",
                "default_marklabel": "",
                "ext_params": "",
                "hover_icon": "",
                "is_open_new_tab": "false",
                "is_outside_channel": "false",
                "jump_url": "",
                "region_type": "0",
                "selected_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-education-select.svg?max_age=7776000",
                "selected_icon_all": "",
                "text_marklabel": "",
                "unselected_icon_all": ""
            },
            "children_list": {},
            "report_infos": {},
            "operations": {},
            "flip_infos": {},
            "static_conf": null
        },
        {
            "id": "",
            "type": "navigation",
            "params": {
                "channel_ename": "art",
                "channel_id": "110676",
                "channel_name": "艺术",
                "channel_type": "乐享生活",
                "default_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-art.svg?max_age=7776000",
                "default_marklabel": "",
                "ext_params": "",
                "hover_icon": "",
                "is_open_new_tab": "false",
                "is_outside_channel": "false",
                "jump_url": "",
                "region_type": "0",
                "selected_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-art-select.svg?max_age=7776000",
                "selected_icon_all": "",
                "text_marklabel": "",
                "unselected_icon_all": ""
            },
            "children_list": {},
            "report_infos": {},
            "operations": {},
            "flip_infos": {},
            "static_conf": null
        },
        {
            "id": "",
            "type": "navigation",
            "params": {
                "channel_ename": "finance",
                "channel_id": "100168",
                "channel_name": "财经",
                "channel_type": "资讯前沿",
                "default_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-finance.svg?max_age=7776000",
                "default_marklabel": "",
                "ext_params": "",
                "hover_icon": "",
                "is_open_new_tab": "false",
                "is_outside_channel": "false",
                "jump_url": "",
                "region_type": "0",
                "selected_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-finance-select.svg?max_age=7776000",
                "selected_icon_all": "",
                "text_marklabel": "",
                "unselected_icon_all": ""
            },
            "children_list": {},
            "report_infos": {},
            "operations": {},
            "flip_infos": {},
            "static_conf": null
        },
        {
            "id": "",
            "type": "navigation",
            "params": {
                "channel_ename": "life",
                "channel_id": "100114",
                "channel_name": "生活",
                "channel_type": "乐享生活",
                "default_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-life.svg?max_age=7776000",
                "default_marklabel": "",
                "ext_params": "",
                "hover_icon": "",
                "is_open_new_tab": "false",
                "is_outside_channel": "false",
                "jump_url": "",
                "region_type": "0",
                "selected_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-life-select.svg?max_age=7776000",
                "selected_icon_all": "",
                "text_marklabel": "",
                "unselected_icon_all": ""
            },
            "children_list": {},
            "report_infos": {},
            "operations": {},
            "flip_infos": {},
            "static_conf": null
        },
        {
            "id": "",
            "type": "navigation",
            "params": {
                "channel_ename": "fashion",
                "channel_id": "100112",
                "channel_name": "时尚",
                "channel_type": "乐享生活",
                "default_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-fashion.svg?max_age=7776000",
                "default_marklabel": "",
                "ext_params": "",
                "hover_icon": "",
                "is_open_new_tab": "false",
                "is_outside_channel": "false",
                "jump_url": "",
                "region_type": "0",
                "selected_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-fashion-select.svg?max_age=7776000",
                "selected_icon_all": "",
                "text_marklabel": "",
                "unselected_icon_all": ""
            },
            "children_list": {},
            "report_infos": {},
            "operations": {},
            "flip_infos": {},
            "static_conf": null
        },
        {
            "id": "",
            "type": "navigation",
            "params": {
                "channel_ename": "health",
                "channel_id": "110511",
                "channel_name": "健康",
                "channel_type": "乐享生活",
                "default_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-health.svg?max_age=7776000",
                "default_marklabel": "",
                "ext_params": "",
                "hover_icon": "",
                "is_open_new_tab": "false",
                "is_outside_channel": "false",
                "jump_url": "",
                "region_type": "0",
                "selected_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-health-select.svg?max_age=7776000",
                "selected_icon_all": "",
                "text_marklabel": "",
                "unselected_icon_all": ""
            },
            "children_list": {},
            "report_infos": {},
            "operations": {},
            "flip_infos": {},
            "static_conf": null
        },
        {
            "id": "",
            "type": "navigation",
            "params": {
                "channel_ename": "baby",
                "channel_id": "100104",
                "channel_name": "育儿",
                "channel_type": "乐享生活",
                "default_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-baby.svg?max_age=7776000",
                "default_marklabel": "",
                "ext_params": "",
                "hover_icon": "",
                "is_open_new_tab": "false",
                "is_outside_channel": "false",
                "jump_url": "",
                "region_type": "0",
                "selected_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-baby-select.svg?max_age=7776000",
                "selected_icon_all": "",
                "text_marklabel": "",
                "unselected_icon_all": ""
            },
            "children_list": {},
            "report_infos": {},
            "operations": {},
            "flip_infos": {},
            "static_conf": null
        },
        {
            "id": "",
            "type": "navigation",
            "params": {
                "channel_ename": "auto",
                "channel_id": "100161",
                "channel_name": "汽车",
                "channel_type": "资讯前沿",
                "default_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-auto.svg?max_age=7776000",
                "default_marklabel": "",
                "ext_params": "",
                "hover_icon": "",
                "is_open_new_tab": "false",
                "is_outside_channel": "false",
                "jump_url": "",
                "region_type": "0",
                "selected_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-auto-select.svg?max_age=7776000",
                "selected_icon_all": "",
                "text_marklabel": "",
                "unselected_icon_all": ""
            },
            "children_list": {},
            "report_infos": {},
            "operations": {},
            "flip_infos": {},
            "static_conf": null
        },
        {
            "id": "",
            "type": "navigation",
            "params": {
                "channel_ename": "",
                "channel_id": "00000",
                "channel_name": "棋牌游戏库",
                "channel_type": "体育游戏",
                "default_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-chesscards_games.svg?max_age=7776000",
                "default_marklabel": "",
                "ext_params": "",
                "hover_icon": "",
                "is_open_new_tab": "false",
                "is_outside_channel": "true",
                "jump_url": "https://iwan.video.qq.com/game-community/game-center/home?ztid=r9b76oy3p4\u0026iwankey=iwan_channel-10357146_rpk",
                "region_type": "0",
                "selected_icon": "https://vm.gtimg.cn/z/static/channel-icons/left-chesscards_games-select.svg?max_age=7776000",
                "selected_icon_all": "",
                "text_marklabel": "",
                "unselected_icon_all": ""
            },
            "children_list": {},
            "report_infos": {},
            "operations": {},
            "flip_infos": {},
            "static_conf": null
        }
    ]




export default nav